# Generated by Django 4.2.2 on 2023-10-02 14:33

import Mountain_peaks.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=64, verbose_name='фамилия')),
                ('name', models.CharField(max_length=64, verbose_name='имя')),
                ('patronymic', models.CharField(max_length=64, verbose_name='отчество')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='электронная почта')),
                ('telephone', models.CharField(max_length=16, verbose_name='номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=64, verbose_name='широта')),
                ('longitude', models.FloatField(max_length=64, verbose_name='долгота')),
                ('height', models.IntegerField(verbose_name='высота')),
            ],
            options={
                'verbose_name': 'Координаты',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('', 'не указано'), ('1a', '1A'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('4a', '4А'), ('4b', '4Б'), ('5a', '5А'), ('5b', '5Б')], default='', max_length=3, verbose_name='Зима')),
                ('spring', models.CharField(choices=[('', 'не указано'), ('1a', '1A'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('4a', '4А'), ('4b', '4Б'), ('5a', '5А'), ('5b', '5Б')], default='', max_length=3, verbose_name='Весна')),
                ('summer', models.CharField(choices=[('', 'не указано'), ('1a', '1A'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('4a', '4А'), ('4b', '4Б'), ('5a', '5А'), ('5b', '5Б')], default='', max_length=3, verbose_name='Лето')),
                ('autumn', models.CharField(choices=[('', 'не указано'), ('1a', '1A'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('4a', '4А'), ('4b', '4Б'), ('5a', '5А'), ('5b', '5Б')], default='', max_length=3, verbose_name='Осень')),
            ],
            options={
                'verbose_name': 'Уровень сложности',
            },
        ),
        migrations.CreateModel(
            name='Peak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default=None, max_length=128, verbose_name='страна')),
                ('category', models.CharField(choices=[('', 'не задано'), ('PA', 'перевал'), ('MP', 'горная вершина'), ('GO', 'ущелье'), ('PL', 'плато')], default='', max_length=3, verbose_name='категория высоты')),
                ('title', models.CharField(max_length=128, verbose_name='название')),
                ('other_titles', models.CharField(max_length=128, verbose_name='другое название')),
                ('connect', models.TextField(default='', verbose_name='соединение')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'новый'), ('pending', 'на модерации'), ('accepted', 'принят'), ('rejected', 'не принят')], default='new', max_length=10, verbose_name='статус')),
                ('activities', models.CharField(choices=[('', 'не задано'), ('foot', 'пеший'), ('bike', 'велосипед'), ('car', 'автомобиль'), ('motorbike', 'мотоцикл')], default='', max_length=64, verbose_name='активность')),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mountain_peaks.coordinate', verbose_name='координаты')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mountain_peaks.level', verbose_name='уровень сложности')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Mountain_peaks.author', verbose_name='автор')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='название')),
                ('photo', models.ImageField(upload_to=Mountain_peaks.models.get_image_path, verbose_name='фотография')),
                ('peak', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Mountain_peaks.peak', verbose_name='вершина')),
            ],
            options={
                'verbose_name': 'Изображение',
            },
        ),
    ]
